name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet core sdk 5
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Publish dotnet core project
      run: dotnet publish pu-test.csproj -c Release -o release --nologo
    - name: Change base tab in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/pu-test\/" \/>/g' release/wwwroot/index.html
    - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
